input glyph;
beginglyph;
input ./glyphs/include/ഡ;

p:=p+1;
input ./glyphs/include/ഢ;
paths[2] := paths[2] shifted (0.56mw, -1.1m) xscaled 0.8 yscaled 0.75 ;
strokes[2] := strokes[2] shifted (0.56mw, -1.1m) xscaled 0.8 yscaled 0.75 ;
paths[3] := paths[3] shifted (0.56mw, -1.1m) xscaled 0.8 yscaled 0.75;
strokes[3] := strokes[3] shifted (0.56mw, -1.1m) xscaled 0.8 yscaled 0.75;



anchor( "vc", point 5 of paths[0]);

endglyph;
